package com.example.chatassignment.Room.Database

import android.content.Context
import android.os.AsyncTask
import androidx.annotation.NonNull
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.sqlite.db.SupportSQLiteDatabase
import com.example.chatassignment.Helpers.Converters
import com.example.chatassignment.Models.Message
import com.example.chatassignment.Models.User
import com.example.chatassignment.R
import com.example.chatassignment.Room.DAOs.MessageDao
import com.example.chatassignment.Room.DAOs.UserDao

//The database for our application with the corresponding entities used
@Database(entities = [Message::class, User::class], version = 1, exportSchema = false)
@TypeConverters(Converters::class)
abstract class ApplicationDatabase : RoomDatabase() {

    abstract fun messageDao(): MessageDao
    abstract fun userDao(): UserDao

    companion object {

        @Volatile
        private var INSTANCE: ApplicationDatabase? = null

        fun getDatabase(context: Context): ApplicationDatabase? {
            if (INSTANCE == null) {
                synchronized(ApplicationDatabase::class.java) {
                    if (INSTANCE == null) {
                        INSTANCE = Room.databaseBuilder(
                            context.applicationContext,
                            ApplicationDatabase::class.java, "message_database"
                        )
                            .addCallback(roomCallBack)
                            .build()

                    }
                }
            }
            return INSTANCE
        }

        //Callback used to prepopulate database
        private val roomCallBack: Callback = object : Callback() {
            override fun onCreate(@NonNull db: SupportSQLiteDatabase) {
                super.onCreate(db)
                INSTANCE?.let {
                    PopulateDbAsyncTask(
                        it
                    ).execute()
                }
            }

        }

        internal class PopulateDbAsyncTask(db: ApplicationDatabase) :
            AsyncTask<Void, Void, Void>() {

            val userDao = db.userDao()
            override fun doInBackground(vararg p0: Void?): Void? {
                //Insert 200 users into database
                userDao.insertUser(
                    User(
                        1,
                        "Thaer",
                        "",
                        null,
                        R.drawable.stevejobsimage
                    )
                )
                userDao.insertUser(
                    User(
                        2,
                        "Rami",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        3,
                        "Abdallah",
                        "",
                        null,
                        R.drawable.manpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        4,
                        "Khaled",
                        "",
                        null,
                        R.drawable.manpicture3
                    )
                )
                userDao.insertUser(
                    User(
                        5,
                        "Diala",
                        "",
                        null,
                        R.drawable.womanpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        6,
                        "Lara",
                        "",
                        null,
                        R.drawable.womanpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        7,
                        "Hasan",
                        "",
                        null,
                        R.drawable.manpicture4
                    )
                )
                userDao.insertUser(
                    User(
                        8,
                        "Abbas",
                        "",
                        null,
                        R.drawable.manpicture5
                    )
                )
                userDao.insertUser(
                    User(
                        9,
                        "Raed",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        10,
                        "Maya",
                        "",
                        null,
                        R.drawable.womanpicture3
                    )
                )
                userDao.insertUser(
                    User(
                        11,
                        "Raneem",
                        "",
                        null,
                        R.drawable.womanpicture4
                    )
                )
                userDao.insertUser(
                    User(
                        12,
                        "Rawan",
                        "",
                        null,
                        R.drawable.womanpicture5
                    )
                )
                userDao.insertUser(
                    User(
                        13,
                        "Mira",
                        "",
                        null,
                        R.drawable.womanpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        14,
                        "Maram",
                        "",
                        null,
                        R.drawable.womanpicture7
                    )
                )
                userDao.insertUser(
                    User(
                        15,
                        "Zeinab",
                        "",
                        null,
                        R.drawable.womanpicture8
                    )
                )
                userDao.insertUser(
                    User(
                        16,
                        "Elie",
                        "",
                        null,
                        R.drawable.manpicture7
                    )
                )
                userDao.insertUser(
                    User(
                        17,
                        "Rimah",
                        "",
                        null,
                        R.drawable.manpicture8
                    )
                )
                userDao.insertUser(
                    User(
                        18,
                        "Ayman",
                        "",
                        null,
                        R.drawable.manpicture9
                    )
                )
                userDao.insertUser(
                    User(
                        19,
                        "Antoine",
                        "",
                        null,
                        R.drawable.manpicture10
                    )
                )
                userDao.insertUser(
                    User(
                        20,
                        "Reem",
                        "",
                        null,
                        R.drawable.womanpicture9
                    )
                )
                userDao.insertUser(
                    User(
                        21,
                        "Ali",
                        "",
                        null,
                        R.drawable.manpicture11
                    )
                )
                userDao.insertUser(
                    User(
                        22,
                        "Jullanar",
                        "",
                        null,
                        R.drawable.womanpicture10
                    )
                )
                userDao.insertUser(
                    User(
                        23,
                        "Mohammad",
                        "",
                        null,
                        R.drawable.manpicture12
                    )
                )
                userDao.insertUser(
                    User(
                        24,
                        "Nadim",
                        "",
                        null,
                        R.drawable.manpicture13
                    )
                )
                userDao.insertUser(
                    User(
                        25,
                        "Anwar",
                        "",
                        null,
                        R.drawable.manpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        26,
                        "Nathalie",
                        "",
                        null,
                        R.drawable.womanpicture11
                    )
                )
                userDao.insertUser(
                    User(
                        27,
                        "Salman",
                        "",
                        null,
                        R.drawable.manpicture15
                    )
                )
                userDao.insertUser(
                    User(
                        28,
                        "Lama",
                        "",
                        null,
                        R.drawable.womanpicture16
                    )
                )
                userDao.insertUser(
                    User(
                        29,
                        "Riwa",
                        "",
                        null,
                        R.drawable.womanpicture17
                    )
                )
                userDao.insertUser(
                    User(
                        30,
                        "Layla",
                        "",
                        null,
                        R.drawable.womanpicture18
                    )
                )
                userDao.insertUser(
                    User(
                        31,
                        "Youssef",
                        "",
                        null,
                        R.drawable.manpicture16
                    )
                )
                userDao.insertUser(
                    User(
                        32,
                        "Hussein",
                        "",
                        null,
                        R.drawable.manpicture17
                    )
                )
                userDao.insertUser(
                    User(
                        33,
                        "Rayan",
                        "",
                        null,
                        R.drawable.manpicture18
                    )
                )
                userDao.insertUser(
                    User(
                        34,
                        "Wassim",
                        "",
                        null,
                        R.drawable.manpicture19
                    )
                )
                userDao.insertUser(
                    User(
                        35,
                        "Sandra",
                        "",
                        null,
                        R.drawable.womanpicture19
                    )
                )
                userDao.insertUser(
                    User(
                        36,
                        "Karam",
                        "",
                        null,
                        R.drawable.manpicture20
                    )
                )
                userDao.insertUser(
                    User(
                        37,
                        "Rafeh",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        38,
                        "Remi",
                        "",
                        null,
                        R.drawable.womanpicture20
                    )
                )
                userDao.insertUser(
                    User(
                        39,
                        "Nadine",
                        "",
                        null,
                        R.drawable.womanpicture21
                    )
                )
                userDao.insertUser(
                    User(
                        40,
                        "Suzanne",
                        "",
                        null,
                        R.drawable.womanpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        41,
                        "Shames",
                        "",
                        null,
                        R.drawable.womanpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        42,
                        "Bassam",
                        "",
                        null,
                        R.drawable.manpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        43,
                        "Rola",
                        "",
                        null,
                        R.drawable.womanpicture3
                    )
                )
                userDao.insertUser(
                    User(
                        44,
                        "Rana",
                        "",
                        null,
                        R.drawable.womanpicture4
                    )
                )
                userDao.insertUser(
                    User(
                        45,
                        "Dawood",
                        "",
                        null,
                        R.drawable.manpicture3
                    )
                )
                userDao.insertUser(
                    User(
                        46,
                        "Rasheed",
                        "",
                        null,
                        R.drawable.manpicture4
                    )
                )
                userDao.insertUser(
                    User(
                        47,
                        "Jawad",
                        "",
                        null,
                        R.drawable.manpicture5
                    )
                )
                userDao.insertUser(
                    User(
                        48,
                        "Lina",
                        "",
                        null,
                        R.drawable.womanpicture5
                    )
                )
                userDao.insertUser(
                    User(
                        49,
                        "Sara",
                        "",
                        null,
                        R.drawable.womanpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        50,
                        "Amani",
                        "",
                        null,
                        R.drawable.womanpicture7
                    )
                )
                userDao.insertUser(
                    User(
                        51,
                        "Wafaa",
                        "",
                        null,
                        R.drawable.womanpicture8
                    )
                )
                userDao.insertUser(
                    User(
                        52,
                        "Amira",
                        "",
                        null,
                        R.drawable.womanpicture9
                    )
                )
                userDao.insertUser(
                    User(
                        53,
                        "Maher",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        54,
                        "Joseph",
                        "",
                        null,
                        R.drawable.manpicture7
                    )
                )
                userDao.insertUser(
                    User(
                        55,
                        "Carole",
                        "",
                        null,
                        R.drawable.womanpicture10
                    )
                )
                userDao.insertUser(
                    User(
                        56,
                        "Ghina",
                        "",
                        null,
                        R.drawable.womanpicture11
                    )
                )
                userDao.insertUser(
                    User(
                        57,
                        "Ghinwa",
                        "",
                        null,
                        R.drawable.womanpicture12
                    )
                )
                userDao.insertUser(
                    User(
                        58,
                        "Fadi",
                        "",
                        null,
                        R.drawable.manpicture8
                    )
                )
                userDao.insertUser(
                    User(
                        59,
                        "Bilal",
                        "",
                        null,
                        R.drawable.manpicture9
                    )
                )
                userDao.insertUser(
                    User(
                        60,
                        "Nabila",
                        "",
                        null,
                        R.drawable.womanpicture13
                    )
                )
                userDao.insertUser(
                    User(
                        61,
                        "Firas",
                        "",
                        null,
                        R.drawable.manpicture10
                    )
                )
                userDao.insertUser(
                    User(
                        62,
                        "Mahmood",
                        "",
                        null,
                        R.drawable.manpicture11
                    )
                )
                userDao.insertUser(
                    User(
                        63,
                        "Jihad",
                        "",
                        null,
                        R.drawable.manpicture12
                    )
                )
                userDao.insertUser(
                    User(
                        64,
                        "Charbel",
                        "",
                        null,
                        R.drawable.manpicture13
                    )
                )
                userDao.insertUser(
                    User(
                        65,
                        "Saeed",
                        "",
                        null,
                        R.drawable.manpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        66,
                        "Haidar",
                        "",
                        null,
                        R.drawable.manpicture15
                    )
                )
                userDao.insertUser(
                    User(
                        67,
                        "Adeeb",
                        "",
                        null,
                        R.drawable.manpicture16
                    )
                )
                userDao.insertUser(
                    User(
                        68,
                        "Rony",
                        "",
                        null,
                        R.drawable.manpicture17
                    )
                )
                userDao.insertUser(
                    User(
                        69,
                        "Alissar",
                        "",
                        null,
                        R.drawable.womanpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        70,
                        "Elissa",
                        "",
                        null,
                        R.drawable.womanpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        71,
                        "Nour",
                        "",
                        null,
                        R.drawable.womanpicture16
                    )
                )
                userDao.insertUser(
                    User(
                        72,
                        "Omar",
                        "",
                        null,
                        R.drawable.manpicture18
                    )
                )
                userDao.insertUser(
                    User(
                        73,
                        "George",
                        "",
                        null,
                        R.drawable.manpicture19
                    )
                )
                userDao.insertUser(
                    User(
                        74,
                        "Farah",
                        "",
                        null,
                        R.drawable.womanpicture17
                    )
                )
                userDao.insertUser(
                    User(
                        75,
                        "Nariman",
                        "",
                        null,
                        R.drawable.womanpicture18
                    )
                )
                userDao.insertUser(
                    User(
                        76,
                        "Ghada",
                        "",
                        null,
                        R.drawable.womanpicture19
                    )
                )
                userDao.insertUser(
                    User(
                        77,
                        "Ghadi",
                        "",
                        null,
                        R.drawable.manpicture20
                    )
                )
                userDao.insertUser(
                    User(
                        78,
                        "Ribal",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        79,
                        "Ragheed",
                        "",
                        null,
                        R.drawable.manpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        80,
                        "Malak",
                        "",
                        null,
                        R.drawable.womanpicture21
                    )
                )
                userDao.insertUser(
                    User(
                        81,
                        "Samir",
                        "",
                        null,
                        R.drawable.manpicture3
                    )
                )
                userDao.insertUser(
                    User(
                        82,
                        "Sameera",
                        "",
                        null,
                        R.drawable.womanpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        83,
                        "Khalil",
                        "",
                        null,
                        R.drawable.manpicture4
                    )
                )
                userDao.insertUser(
                    User(
                        84,
                        "Janan",
                        "",
                        null,
                        R.drawable.womanpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        85,
                        "Louay",
                        "",
                        null,
                        R.drawable.manpicture5
                    )
                )
                userDao.insertUser(
                    User(
                        86,
                        "Lewaa",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        87,
                        "Nermin",
                        "",
                        null,
                        R.drawable.womanpicture3
                    )
                )
                userDao.insertUser(
                    User(
                        88,
                        "Grace",
                        "",
                        null,
                        R.drawable.womanpicture4
                    )
                )
                userDao.insertUser(
                    User(
                        89,
                        "Razan",
                        "",
                        null,
                        R.drawable.womanpicture5
                    )
                )
                userDao.insertUser(
                    User(
                        90,
                        "Nohad",
                        "",
                        null,
                        R.drawable.manpicture7
                    )
                )
                userDao.insertUser(
                    User(
                        91,
                        "Mazen",
                        "",
                        null,
                        R.drawable.manpicture8
                    )
                )
                userDao.insertUser(
                    User(
                        92,
                        "Imad",
                        "",
                        null,
                        R.drawable.manpicture9
                    )
                )
                userDao.insertUser(
                    User(
                        93,
                        "Moeen",
                        "",
                        null,
                        R.drawable.manpicture10
                    )
                )
                userDao.insertUser(
                    User(
                        94,
                        "Nagham",
                        "",
                        null,
                        R.drawable.womanpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        95,
                        "Pascal",
                        "",
                        null,
                        R.drawable.womanpicture7
                    )
                )
                userDao.insertUser(
                    User(
                        96,
                        "Dalia",
                        "",
                        null,
                        R.drawable.womanpicture8
                    )
                )
                userDao.insertUser(
                    User(
                        97,
                        "Jean",
                        "",
                        null,
                        R.drawable.manpicture11
                    )
                )
                userDao.insertUser(
                    User(
                        98,
                        "Zahra",
                        "",
                        null,
                        R.drawable.womanpicture9
                    )
                )
                userDao.insertUser(
                    User(
                        99,
                        "Maysaa",
                        "",
                        null,
                        R.drawable.womanpicture10
                    )
                )
                userDao.insertUser(
                    User(
                        100,
                        "Lynn",
                        "",
                        null,
                        R.drawable.womanpicture11
                    )
                )
                userDao.insertUser(
                    User(
                        101,
                        "Nizam",
                        "",
                        null,
                        R.drawable.manpicture12
                    )
                )
                userDao.insertUser(
                    User(
                        102,
                        "Tarek",
                        "",
                        null,
                        R.drawable.manpicture13
                    )
                )
                userDao.insertUser(
                    User(
                        103,
                        "Hilal",
                        "",
                        null,
                        R.drawable.manpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        104,
                        "Jessica",
                        "",
                        null,
                        R.drawable.womanpicture12
                    )
                )
                userDao.insertUser(
                    User(
                        105,
                        "Rouba",
                        "",
                        null,
                        R.drawable.womanpicture13
                    )
                )
                userDao.insertUser(
                    User(
                        106,
                        "Najwa",
                        "",
                        null,
                        R.drawable.womanpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        107,
                        "Jeremy",
                        "",
                        null,
                        R.drawable.manpicture15
                    )
                )
                userDao.insertUser(
                    User(
                        108,
                        "Edgar",
                        "",
                        null,
                        R.drawable.manpicture16
                    )
                )
                userDao.insertUser(
                    User(
                        109,
                        "David",
                        "",
                        null,
                        R.drawable.manpicture17
                    )
                )
                userDao.insertUser(
                    User(
                        110,
                        "Julia",
                        "",
                        null,
                        R.drawable.womanpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        111,
                        "Flynn",
                        "",
                        null,
                        R.drawable.manpicture18
                    )
                )
                userDao.insertUser(
                    User(
                        112,
                        "Fletcher",
                        "",
                        null,
                        R.drawable.manpicture19
                    )
                )
                userDao.insertUser(
                    User(
                        113,
                        "Mostafa",
                        "",
                        null,
                        R.drawable.manpicture20
                    )
                )
                userDao.insertUser(
                    User(
                        114,
                        "John",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        115,
                        "Jessy",
                        "",
                        null,
                        R.drawable.womanpicture16
                    )
                )
                userDao.insertUser(
                    User(
                        116,
                        "Ray",
                        "",
                        null,
                        R.drawable.manpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        117,
                        "Jay",
                        "",
                        null,
                        R.drawable.manpicture3
                    )
                )
                userDao.insertUser(
                    User(
                        118,
                        "Kevin",
                        "",
                        null,
                        R.drawable.manpicture4
                    )
                )
                userDao.insertUser(
                    User(
                        119,
                        "Albert",
                        "",
                        null,
                        R.drawable.manpicture5
                    )
                )
                userDao.insertUser(
                    User(
                        120,
                        "Jason",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        121,
                        "Patrick",
                        "",
                        null,
                        R.drawable.manpicture7
                    )
                )
                userDao.insertUser(
                    User(
                        122,
                        "Connor",
                        "",
                        null,
                        R.drawable.manpicture8
                    )
                )
                userDao.insertUser(
                    User(
                        123,
                        "Vince",
                        "",
                        null,
                        R.drawable.manpicture9
                    )
                )
                userDao.insertUser(
                    User(
                        124,
                        "Shawn",
                        "",
                        null,
                        R.drawable.manpicture10
                    )
                )
                userDao.insertUser(
                    User(
                        125,
                        "Walaa",
                        "",
                        null,
                        R.drawable.womanpicture17
                    )
                )
                userDao.insertUser(
                    User(
                        126,
                        "Alaa",
                        "",
                        null,
                        R.drawable.manpicture11
                    )
                )
                userDao.insertUser(
                    User(
                        127,
                        "Marcel",
                        "",
                        null,
                        R.drawable.manpicture12
                    )
                )
                userDao.insertUser(
                    User(
                        128,
                        "Allan",
                        "",
                        null,
                        R.drawable.manpicture13
                    )
                )
                userDao.insertUser(
                    User(
                        129,
                        "Cesar",
                        "",
                        null,
                        R.drawable.manpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        130,
                        "Ben",
                        "",
                        null,
                        R.drawable.manpicture15
                    )
                )
                userDao.insertUser(
                    User(
                        131,
                        "Willian",
                        "",
                        null,
                        R.drawable.manpicture16
                    )
                )
                userDao.insertUser(
                    User(
                        132,
                        "William",
                        "",
                        null,
                        R.drawable.manpicture17
                    )
                )
                userDao.insertUser(
                    User(
                        133,
                        "Christian",
                        "",
                        null,
                        R.drawable.manpicture18
                    )
                )
                userDao.insertUser(
                    User(
                        134,
                        "Serge",
                        "",
                        null,
                        R.drawable.manpicture19
                    )
                )
                userDao.insertUser(
                    User(
                        135,
                        "Sami",
                        "",
                        null,
                        R.drawable.manpicture20
                    )
                )
                userDao.insertUser(
                    User(
                        136,
                        "Walid",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        137,
                        "Sahar",
                        "",
                        null,
                        R.drawable.womanpicture18
                    )
                )
                userDao.insertUser(
                    User(
                        138,
                        "Diego",
                        "",
                        null,
                        R.drawable.manpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        139,
                        "Robert",
                        "",
                        null,
                        R.drawable.manpicture3
                    )
                )
                userDao.insertUser(
                    User(
                        140,
                        "Thomas",
                        "",
                        null,
                        R.drawable.manpicture4
                    )
                )
                userDao.insertUser(
                    User(
                        141,
                        "Fletcher",
                        "",
                        null,
                        R.drawable.manpicture5
                    )
                )
                userDao.insertUser(
                    User(
                        142,
                        "Thiago",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        143,
                        "Selena",
                        "",
                        null,
                        R.drawable.womanpicture19
                    )
                )
                userDao.insertUser(
                    User(
                        144,
                        "Emily",
                        "",
                        null,
                        R.drawable.womanpicture20
                    )
                )
                userDao.insertUser(
                    User(
                        145,
                        "Massoud",
                        "",
                        null,
                        R.drawable.manpicture7
                    )
                )
                userDao.insertUser(
                    User(
                        146,
                        "Kareem",
                        "",
                        null,
                        R.drawable.manpicture8
                    )
                )
                userDao.insertUser(
                    User(
                        147,
                        "Saad",
                        "",
                        null,
                        R.drawable.manpicture9
                    )
                )
                userDao.insertUser(
                    User(
                        148,
                        "Melissa",
                        "",
                        null,
                        R.drawable.womanpicture21
                    )
                )
                userDao.insertUser(
                    User(
                        149,
                        "Layal",
                        "",
                        null,
                        R.drawable.womanpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        150,
                        "Jennifer",
                        "",
                        null,
                        R.drawable.womanpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        151,
                        "Sean",
                        "",
                        null,
                        R.drawable.manpicture10
                    )
                )
                userDao.insertUser(
                    User(
                        152,
                        "Steve",
                        "",
                        null,
                        R.drawable.manpicture11
                    )
                )
                userDao.insertUser(
                    User(
                        153,
                        "Chris",
                        "",
                        null,
                        R.drawable.manpicture12
                    )
                )
                userDao.insertUser(
                    User(
                        154,
                        "Luis",
                        "",
                        null,
                        R.drawable.manpicture13
                    )
                )
                userDao.insertUser(
                    User(
                        155,
                        "Mark",
                        "",
                        null,
                        R.drawable.manpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        156,
                        "Patricia",
                        "",
                        null,
                        R.drawable.womanpicture3
                    )
                )
                userDao.insertUser(
                    User(
                        157,
                        "Alexis",
                        "",
                        null,
                        R.drawable.womanpicture4
                    )
                )
                userDao.insertUser(
                    User(
                        158,
                        "Ronnie",
                        "",
                        null,
                        R.drawable.manpicture15
                    )
                )
                userDao.insertUser(
                    User(
                        159,
                        "Zack",
                        "",
                        null,
                        R.drawable.manpicture16
                    )
                )
                userDao.insertUser(
                    User(
                        160,
                        "Ronald",
                        "",
                        null,
                        R.drawable.manpicture17
                    )
                )
                userDao.insertUser(
                    User(
                        161,
                        "Matteo",
                        "",
                        null,
                        R.drawable.manpicture18
                    )
                )
                userDao.insertUser(
                    User(
                        162,
                        "Adam",
                        "",
                        null,
                        R.drawable.manpicture19
                    )
                )
                userDao.insertUser(
                    User(
                        163,
                        "Carl",
                        "",
                        null,
                        R.drawable.manpicture20
                    )
                )
                userDao.insertUser(
                    User(
                        164,
                        "Sally",
                        "",
                        null,
                        R.drawable.womanpicture5
                    )
                )
                userDao.insertUser(
                    User(
                        165,
                        "Catherine",
                        "",
                        null,
                        R.drawable.womanpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        166,
                        "Samantha",
                        "",
                        null,
                        R.drawable.womanpicture7
                    )
                )
                userDao.insertUser(
                    User(
                        167,
                        "Isabelle",
                        "",
                        null,
                        R.drawable.womanpicture8
                    )
                )
                userDao.insertUser(
                    User(
                        168,
                        "Chelsea",
                        "",
                        null,
                        R.drawable.womanpicture9
                    )
                )
                userDao.insertUser(
                    User(
                        169,
                        "Jamie",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        170,
                        "Margarette",
                        "",
                        null,
                        R.drawable.womanpicture10
                    )
                )
                userDao.insertUser(
                    User(
                        171,
                        "Aline",
                        "",
                        null,
                        R.drawable.womanpicture11
                    )
                )
                userDao.insertUser(
                    User(
                        172,
                        "Heather",
                        "",
                        null,
                        R.drawable.womanpicture12
                    )
                )
                userDao.insertUser(
                    User(
                        173,
                        "Lea",
                        "",
                        null,
                        R.drawable.womanpicture13
                    )
                )
                userDao.insertUser(
                    User(
                        174,
                        "Lilly",
                        "",
                        null,
                        R.drawable.womanpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        175,
                        "Diane",
                        "",
                        null,
                        R.drawable.womanpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        176,
                        "Tamara",
                        "",
                        null,
                        R.drawable.womanpicture16
                    )
                )
                userDao.insertUser(
                    User(
                        177,
                        "Madeline",
                        "",
                        null,
                        R.drawable.womanpicture17
                    )
                )
                userDao.insertUser(
                    User(
                        178,
                        "April",
                        "",
                        null,
                        R.drawable.womanpicture18
                    )
                )
                userDao.insertUser(
                    User(
                        179,
                        "Gabriel",
                        "",
                        null,
                        R.drawable.manpicture2
                    )
                )
                userDao.insertUser(
                    User(
                        180,
                        "Beth",
                        "",
                        null,
                        R.drawable.womanpicture19
                    )
                )
                userDao.insertUser(
                    User(
                        181,
                        "Bertha",
                        "",
                        null,
                        R.drawable.womanpicture20
                    )
                )
                userDao.insertUser(
                    User(
                        182,
                        "Rowan",
                        "",
                        null,
                        R.drawable.manpicture3
                    )
                )
                userDao.insertUser(
                    User(
                        183,
                        "Frank",
                        "",
                        null,
                        R.drawable.manpicture4
                    )
                )
                userDao.insertUser(
                    User(
                        184,
                        "Tristan",
                        "",
                        null,
                        R.drawable.manpicture5
                    )
                )
                userDao.insertUser(
                    User(
                        185,
                        "Felix",
                        "",
                        null,
                        R.drawable.manpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        186,
                        "Oscar",
                        "",
                        null,
                        R.drawable.manpicture7
                    )
                )
                userDao.insertUser(
                    User(
                        187,
                        "Will",
                        "",
                        null,
                        R.drawable.manpicture8
                    )
                )
                userDao.insertUser(
                    User(
                        188,
                        "Tyler",
                        "",
                        null,
                        R.drawable.manpicture9
                    )
                )
                userDao.insertUser(
                    User(
                        189,
                        "Andre",
                        "",
                        null,
                        R.drawable.manpicture10
                    )
                )
                userDao.insertUser(
                    User(
                        190,
                        "Lorenzo",
                        "",
                        null,
                        R.drawable.manpicture11
                    )
                )
                userDao.insertUser(
                    User(
                        191,
                        "Walter",
                        "",
                        null,
                        R.drawable.manpicture12
                    )
                )
                userDao.insertUser(
                    User(
                        192,
                        "Moussa",
                        "",
                        null,
                        R.drawable.manpicture13
                    )
                )
                userDao.insertUser(
                    User(
                        193,
                        "Hillary",
                        "",
                        null,
                        R.drawable.womanpicture21
                    )
                )
                userDao.insertUser(
                    User(
                        194,
                        "Rachelle",
                        "",
                        null,
                        R.drawable.womanpicture1
                    )
                )
                userDao.insertUser(
                    User(
                        195,
                        "Joey",
                        "",
                        null,
                        R.drawable.manpicture14
                    )
                )
                userDao.insertUser(
                    User(
                        196,
                        "Raphael",
                        "",
                        null,
                        R.drawable.manpicture15
                    )
                )
                userDao.insertUser(
                    User(
                        197,
                        "Luka",
                        "",
                        null,
                        R.drawable.manpicture16
                    )
                )
                userDao.insertUser(
                    User(
                        198,
                        "Gregor",
                        "",
                        null,
                        R.drawable.manpicture17
                    )
                )
                userDao.insertUser(
                    User(
                        199,
                        "Peter",
                        "",
                        null,
                        R.drawable.manpicture18
                    )
                )
                userDao.insertUser(
                    User(
                        200,
                        "Toby",
                        "",
                        null,
                        R.drawable.manpicture19
                    )
                )
                return null
            }
        }
    }
}
